"""Five-step workflow, observability and approval-controlled maintenance."""
from scene_helpers import (
    DOCS,
    REPOSITORY,
    head,
    icon,
    image,
    network,
    network_node,
    slide,
)

workflow_steps = [('file', 'Refinar o pedido'), ('book', 'Gerar o PRD.md'), ('folder', 'Preparar o template'), ('code', 'Executar a sprint'), ('check', 'Revisar, corrigir e versionar')]
workflow_buttons = ''.join(f'<button class="workflow-step" data-workflow-step="{i}" aria-pressed="false"><span class="number">{i + 1:02d}</span>{icon(symbol)}<strong>{title}</strong></button>' for i, (symbol, title) in enumerate(workflow_steps))

workers = ''.join('<div class="worker" data-node-id="' + identifier + '">' + image(file, name, cls) + '<div><h3>' + title + '</h3><p>' + detail + '</p></div></div>' for identifier, file, name, cls, title, detail in [
    ('claude', 'claude-code-lobe-color.svg', 'Claude Code, reprodução Lobe Icons', 'logo', 'Implementação', 'Filho Hermes → Claude Code pela CLI'),
    ('codex', 'openai-lobe.svg', 'OpenAI, reprodução Lobe Icons', 'logo pad', 'Revisão e testes', 'Filho Hermes → Codex CLI'),
    ('opencode', 'opencode-logo-dark.svg', 'OpenCode', 'logo', 'Investigação delimitada', 'Filho Hermes → OpenCode pela CLI'),
])

app_services = ''.join('<div class="service">' + image(file, name) + '<span>' + name + '</span></div>' for file, name in [
    ('django-negative.svg', 'Django'), ('postgresql.svg', 'PostgreSQL'), ('rabbitmq.svg', 'RabbitMQ'), ('redis.svg', 'Redis'),
])

SLIDES = [
    slide(11, 'workflow', 'Cinco passos para construir e revisar o projeto', 'Workflow de IA Assistida · PycodeBR', 'yellow',
          head('Cinco passos para construir<br class="desktop-break"> e revisar o projeto.') + '<div class="scene"><div class="workflow-steps" role="group" aria-label="Etapas do Workflow de IA Assistida">' + workflow_buttons + '</div><div class="workflow-detail"><div class="step-big" data-step-number></div><div><h3 data-step-title></h3><p data-step-body></p></div><div class="artifact-card">' + icon('file') + '<div><strong data-step-file></strong><span data-step-output></span></div></div></div><div class="sprint-loop">' + icon('loop') + '<span><strong>04 Sprint → 05 Review, correções e commit → 04 Próxima sprint</strong></span><span>Deploy previsto desde o início.</span></div><p class="caption">Workflow ensinado na Imersão IA Builders e no IA Master Elite.</p></div>',
          'Os cinco passos são Prompt bruto → Prompt refinado; Prompt refinado → PRD.md; PRD.md → Start Template; Start Template → Sprint; Sprint → Review, Correções e Commit. O quinto passo se repete por sprint; deploy não o substitui.', [REPOSITORY + '/blob/main/materiais/workflow-ia-assistida.md'], scene='workflow'),
    slide(12, 'harness', 'O Hermes acompanha a sprint e pode dividir o trabalho', 'Harness e delegação', 'purple',
          head('O Hermes acompanha a sprint<br class="desktop-break"> e pode dividir o trabalho.') + '<div class="scene">' + network('<div class="network-node orchestrator" data-node-id="hermes">' + image('hermes-logo-dark.png', 'Hermes Agent', '') + '<h3>Hermes principal</h3><p>PRD, contexto e skills.</p><p class="small">delegate_task</p></div><div class="workers"><p class="small">Subtarefas independentes, em paralelo</p>' + workers + '</div><div class="network-node review-node" data-node-id="review">' + icon('check') + '<h3>Integração conferida</h3><p>Diff, testes e critérios da sprint.</p></div>', [['hermes', 'claude', '#b9a2f8'], ['hermes', 'codex', '#7dd3fc'], ['hermes', 'opencode', '#e8f4ba'], ['claude', 'review', '#b9a2f8'], ['codex', 'review', '#7dd3fc'], ['opencode', 'review', '#e8f4ba']], 'orchestration-grid') + '<p class="note-line">delegate_task cria filhos Hermes. As CLIs externas são chamadas pelo terminal, com ambientes e acessos preparados.</p></div>',
          'O Hermes pode executar o workflow como harness de desenvolvimento e delegar subtarefas delimitadas. Filhos Hermes podem invocar outros harnesses pela CLI, mas a revisão e a integração permanecem explícitas.', [DOCS + 'user-guide/features/delegation', 'https://opencode.ai/docs/']),
    slide(13, 'stack', 'Depois do deploy, o sistema precisa ser acompanhado', 'Stack de deploy e observabilidade', 'orange',
          head('Depois do deploy,<br class="desktop-break"> o sistema precisa ser acompanhado.') + '<div class="scene">' + network('<div class="stack-column">' + network_node('build', 'Código e imagem', 'GitHub → registry', 'GitHub_Invertocat_White_Clearspace.svg') + network_node('edge', 'Entrada HTTPS', 'Traefik e TLS', 'traefik-proxy.svg') + '</div><div class="network-node stack-app" data-node-id="app"><h3>Aplicação e serviços</h3><div class="service-grid">' + app_services + '</div><p class="stack-note">Celery Worker + Beat para tarefas.</p><div class="runtime">' + image('docker-mark-white.svg', 'Docker') + '<span>Docker Swarm · VPS</span></div></div><div class="stack-column">' + network_node('metrics', 'Prometheus', 'Métricas por scrape', 'prometheus-logo.svg') + network_node('logs', 'Loki', 'Logs enviados pelo coletor', 'loki-logo.svg') + network_node('grafana', 'Grafana', 'Painéis e consultas', 'grafana-icon.svg') + '</div>', [['build', 'app', '#7dd3fc'], ['edge', 'app', '#7dd3fc'], ['app', 'metrics', '#e8f4ba'], ['app', 'logs', '#ffb56b'], ['metrics', 'grafana', '#e8f4ba'], ['logs', 'grafana', '#ffb56b']], 'stack-architecture') + '<p class="caption">Base dos encontros Elite #03 e #04. cAdvisor/node-exporter complementam métricas. Alloy é a recomendação atual para coleta de logs.</p></div>',
          'A stack do exemplo SCSI combina aplicação Django, banco e tarefas, Docker Swarm e Traefik. Prometheus coleta métricas, Loki armazena logs e Grafana consulta as fontes. O material histórico usava Promtail; Alloy é atualização recomendada, sem alegar migração de uma implantação.', ['https://docs.docker.com/engine/swarm/services/', 'https://prometheus.io/docs/introduction/overview/', 'https://grafana.com/docs/loki/latest/send-data/promtail/']),
    slide(14, 'monitoria', 'O Hermes cruza métricas, logs e o estado do sistema', 'Observabilidade com IA', 'orange',
          head('O Hermes cruza métricas, logs<br class="desktop-break"> e o estado do sistema.') + '<div class="scene"><div class="observe-grid"><div class="signals panel"><div class="signal-title"><span data-signal-title></span>' + image('grafana-icon.svg', 'Grafana') + '</div><div class="signal-tabs"><button data-signal="latency" aria-pressed="true">Latência</button><button data-signal="queue" aria-pressed="false">Fila</button><button data-signal="errors" aria-pressed="false">Erros</button></div><svg class="signal-chart" viewBox="0 0 480 205" aria-label="Cenário ilustrativo de telemetria"><path class="grid" d="M0 40h480M0 100h480M0 160h480M0 203h480"/><path class="threshold" d="M0 70h480"/><path class="plot" d="M5 180L475 20"/></svg><p class="signal-legend" data-signal-legend></p><div class="log-lines" data-log-line></div></div><div class="telemetry-core"><div class="agent-core">' + image('hermes-logo-dark.png', 'Hermes Agent', '') + '<strong>Hermes Agent</strong></div><div class="mcp-links"><span>MCP do Grafana</span><span>MCP do sistema</span></div></div><div class="investigation"><div class="investigation-step">Investigar<small data-investigation></small></div><div class="investigation-step">Avaliar a ação<small data-action></small></div><div class="investigation-step">Avisar e conferir<small>Canal autorizado e evidências do resultado.</small></div><div class="channel-icons">' + image('whatsapp-simpleicons.svg', 'WhatsApp', 'logo pad') + icon('message') + '<span class="caption">Privado ou equipe</span></div></div></div><div class="telemetry-status">Um alerta por webhook ou uma rotina de coleta inicia a análise.</div><p class="interactive-note">Cenários ilustrativos. Consultas usam janelas e dados atualizados; acesso por MCP não cria o disparador.</p></div>',
          'O observador consulta Grafana MCP e MCP de domínio, cruza sinais do mesmo serviço e período, prepara diagnóstico ou ação dentro da política e comunica por canais autorizados. Webhook ou scheduler são mecanismos separados do MCP. Este encadeamento é uma arquitetura de referência.', ['https://github.com/grafana/mcp-grafana', 'https://grafana.com/docs/grafana/latest/alerting/configure-notifications/manage-contact-points/integrations/webhook-notifier/'], scene='monitoring'),
    slide(15, 'reports', 'Bugs e melhorias podem entrar no mesmo workflow', 'MentorIA · reports e PRs', 'rose',
          head('Bugs e melhorias podem entrar<br class="desktop-break"> no mesmo workflow.') + '<div class="scene"><div class="report-layout"><div class="report-card panel"><span class="section-tag">REPORT DO SISTEMA · EXEMPLO</span><div class="report-kind" style="margin-top:25px"><button data-report="bug" aria-pressed="true">Bug</button><button data-report="feature" aria-pressed="false">Melhoria</button></div><h3 data-report-title></h3><p data-report-description></p><div class="small" data-report-triage></div></div><div><div class="triage-flow"><div class="triage-step"><span class="number">01</span><h3>Analisar e classificar</h3><p>Impacto, contexto e duplicidade.</p></div><div class="triage-step"><span class="number">02</span><h3>Delimitar a mudança</h3><p>Reprodução ou critérios de aceite.</p></div><div class="triage-step"><span class="number">03</span><h3>Implementar e testar</h3><p>Branch isolada, review e correções.</p></div><div class="triage-step"><span class="number">04</span><h3>Abrir a PR</h3><p>Diff, testes, riscos e proposta.</p></div></div><div class="pr-output">' + image('GitHub_Invertocat_White_Clearspace.svg', 'GitHub') + '<span>A mudança chega como uma revisão de código.</span></div></div></div><p class="caption">Exemplo de integração com MentorIA. Um evento do sistema ou uma coleta autorizada fornece a entrada.</p></div>',
          'Blueprint solicitado para MentorIA: reports de bugs e sugestões são classificados, transformados em trabalho delimitado e tratados com branch, testes, revisão e PR. Não afirma que todo o ciclo esteja automatizado na instalação atual.', ['https://pypi.org/project/django-mcp-server/', REPOSITORY + '/blob/main/materiais/observabilidade-e-manutencao.md'], scene='reports'),
    slide(16, 'aprovacao', 'Você revisa a PR antes do merge e do deploy', 'Revisão humana e entrega', 'lime',
          head('Você revisa a PR<br class="desktop-break"> antes do merge e do deploy.') + '<div class="scene"><div class="approval-grid"><div class="pull-request panel"><div class="logo-name">' + image('GitHub_Invertocat_White_Clearspace.svg', 'GitHub') + '<span>PR de exemplo</span></div><h3 data-pr-title></h3><div class="check">Teste do comportamento afetado</div><div class="check">Diff revisável e riscos descritos</div><div class="check">Versão vinculada à aprovação</div></div><div class="approval-phone"><div class="phone-title">' + image('whatsapp-simpleicons.svg', 'WhatsApp', 'logo pad') + '<span>Privado de Felipe</span></div><p data-private-message></p><button class="button primary" data-approve>Aprovar esta revisão</button><button class="button" data-reject>Pedir ajustes</button></div><div class="deployment-steps"><div class="deployment-step">' + icon('merge') + '<span>Merge autorizado</span></div><div class="deployment-step">' + icon('deploy') + '<span>Deploy da versão</span></div><div class="deployment-step">' + icon('check') + '<span>Conferir a correção</span></div><button class="button" data-merge disabled>Simular a entrega</button></div></div><div class="visual-footer"><p class="approval-state" data-approval-state aria-live="polite"></p><button class="button" data-reset-approval>Recomeçar</button></div><p class="interactive-note">Demonstração local, sem enviar mensagens ou alterar repositórios. Mudança na PR exige nova revisão.</p></div>',
          'Felipe recebe uma mensagem privada com a PR e decide. A aprovação se aplica à revisão atual; merge, deploy e confirmação são etapas distintas. A simulação não realiza chamadas externas nem comprova implantação do blueprint.', ['https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches'], scene='approval'),
    slide(17, 'permissoes', 'O que pode agir sozinho precisa estar definido antes', 'Permissões e autonomia', 'yellow',
          head('O que pode agir sozinho<br class="desktop-break"> precisa estar definido antes.') + '<div class="scene"><div class="permission-grid"><div class="permission-zone"><h3>Dentro do escopo autorizado</h3><div class="permission-item">' + icon('monitor') + '<span>Consultar métricas e logs</span></div><div class="permission-item">' + icon('test') + '<span>Investigar e testar em isolamento</span></div><div class="permission-item">' + icon('pull') + '<span>Preparar uma branch e uma PR</span></div><p class="caption">Orçamento, limites de tempo e rastreabilidade.</p></div><div class="permission-zone gate"><h3>Com aprovação definida</h3><div class="permission-item">' + icon('merge') + '<span>Merge da revisão aprovada</span></div><div class="permission-item">' + icon('deploy') + '<span>Deploy no ambiente combinado</span></div><div class="permission-item">' + icon('shield') + '<span>Mudanças sensíveis de dados e acesso</span></div><p class="caption">Controles nas ferramentas, além das instruções.</p></div></div><p class="note-line">Sinais de risco podem antecipar uma investigação. Intervenções seguem regras e verificações próprias.</p></div>',
          'A atuação preventiva tem limites por etapa e risco. Consultas e testes podem ser preautorizados; operações sensíveis e release exigem gates aplicados nas ferramentas, não apenas no prompt.', [DOCS + 'user-guide/security']),
    slide(18, 'materiais', 'Continue com os materiais da palestra', 'Materiais e perguntas', 'lime',
          '<div class="scene"><div><h2>Continue com os<br class="desktop-break"> materiais da palestra.</h2><p class="lead">Workflow, arquitetura, referências e um laboratório local para explorar o fluxo.</p><a class="button primary" data-repository-link href="' + REPOSITORY + '" target="_blank" rel="noopener noreferrer">' + icon('book') + 'Acessar materiais no GitHub</a><p class="repo-url">github.com/pycodebr/<br>pycodebr_python_brasil_2026</p><p class="caption" style="margin-top:30px">Hermes Agent · Nous Research e comunidade<br>Felipe Azambuja · PycodeBR</p></div><div class="material-book"><div class="book"><div class="book-spine"></div><div class="book-symbol">' + image('pycodebr-icon-official.png', 'PycodeBR') + image('python-icon.svg', 'Python') + '</div><div class="book-title">Agentes<br>Autônomos<br>de IA</div><div class="book-credit">Python Brasil 2026</div></div><div class="book-chip">Slides + guias + código</div></div></div>',
          'O repositório público reúne os slides, os materiais de acompanhamento, as fontes e o laboratório. O fechamento reserva cinco minutos para perguntas.', [REPOSITORY, DOCS], 'closing'),
]
